awesome:
  - sindresorhus/awesome
  - vinta/awesome-python
  - awesome-selfhosted/awesome-selfhosted
  - avelino/awesome-go
  - sindresorhus/awesome-nodejs
  - ibraheemdev/modern-unix
awesome-desktop:
  - microsoft/vscode
  - microsoft/terminal
  - microsoft/PowerToys
  - tonsky/FiraCode
  - Fndroid/clash_for_windows_pkg
  - agalwood/Motrix
  - pbatard/rufus
  - Molunerfinn/PicGo
  - videolan/vlc
  - zotero/zotero
  - YerongAI/Office-Tool
  - TheAssassin/AppImageLauncher
awesome-go:
  - spf13/cobra
  - sirupsen/logrus
  - spf13/viper
  - stretchr/testify
  - google/go-github
  - mvdan/sh
  - go-survey/survey
  - pterm/pterm
  - otiai10/copy
awesome-nodejs:
  - vuejs/vue
  - facebook/react
  - vercel/next.js
  - ant-design/ant-design
  - vuepress/vuepress-next
awesome-python:
  - psf/requests
  - Textualize/rich
  - pandas-dev/pandas
  - psf/black
  - httpie/httpie
  - numpy/numpy
  - matplotlib/matplotlib
  - pallets/click
  - mwaskom/seaborn
  - pyinstaller/pyinstaller
  - PyCQA/isort
  - conda/conda
  - tmbo/questionary
  - pappasam/toml-sort
awesome-selfhosted:
  - squidfunk/mkdocs-material
  - upptime/upptime
  - bastienwirtz/homer
  - qkqpttgf/OneManager-php
  - spencerwooo/onedrive-vercel-index
  - vuepress-theme-hope/vuepress-theme-hope
awesome-shell:
  - neovim/neovim
  - junegunn/fzf
  - prettier/prettier
  - tldr-pages/tldr
  - sharkdp/bat
  - rclone/rclone
  - BurntSushi/ripgrep
  - jesseduffield/lazygit
  - cli/cli
  - tmux/tmux
  - httpie/httpie
  - sharkdp/fd
  - stedolan/jq
  - ogham/exa
  - dylanaraps/neofetch
  - dandavison/delta
  - tj/git-extras
  - sharkdp/hyperfine
  - charmbracelet/gum
  - muesli/duf
  - pre-commit/pre-commit
  - charmbracelet/vhs
  - ajeetdsouza/zoxide
  - ocrmypdf/OCRmyPDF
  - orf/gping
  - ClementTsang/bottom
  - bootandy/dust
  - bitwarden/clients
  - gokcehan/lf
  - ogham/dog
  - boyter/scc
  - Textualize/rich-cli
  - dundee/gdu
  - wakatime/wakatime-cli
awesome-zsh:
  - ohmyzsh/ohmyzsh
  - romkatv/powerlevel10k
  - zsh-users/zsh-syntax-highlighting
  - marlonrichert/zsh-autocomplete
  - SukkaW/zsh-proxy
  - conda-incubator/conda-zsh-completion
  - sobolevn/wakatime-zsh-plugin
  - Game4Move78/zsh-bitwarden
