name: CI/CD

on:
  push:
    branches:
      - main

# - [x] Settings > General > Pull Requests > Automatically delete head branches
# - [x] Settings > Actions > General > Workflow permissions > Allow GitHub Actions to create and approve pull requests
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build Executable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: go
        name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build Executable
        run: make build
      - if: runner.os != 'Windows'
        name: Rename Build Artifact
        run: mv bin/* bin/${{ github.event.repository.name }}-${{ runner.os }}-${{ runner.arch }}-py${{ steps.go.outputs.go-version }}
      - if: runner.os == 'Windows'
        name: Rename Build Artifact
        run: mv bin/* bin/${{ github.event.repository.name }}-${{ runner.os }}-${{ runner.arch }}-py${{ steps.go.outputs.go-version }}.exe
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: bin/*
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      releases-created: ${{ steps.release.outputs.releases_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        name: Create GitHub Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: go

  upload:
    name: Upload Release Assets
    needs:
      - build
      - release
    if: needs.release.outputs.releases-created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@master
        with:
          file: artifacts/**/*
          tag: ${{ needs.release.outputs.tag-name }}
          file_glob: true
          overwrite: true
